spring:
  datasource:
    url: jdbc:mysql://82.157.147.88:8023/ccpc?useSSL=false&serverTimezone=UTC
    username: root
    password: ccpc_mysql_root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 30000

  data:
    redis:
      host: 82.157.147.88
      port: 8024
      password: ccpc_redis_root
      timeout: 2000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  upload:
    path: C:/ccpc-backend/file/
  url:
    prefix: http://localhost:8021/api/file/

